# NOTE: THIS MOD IS IN BETA AND INJECTS INTO MANY DIFFERENT MODS
# STABILITY NOT GUARANTEED, PROCEED AT YOUR OWN RISK
# Celestweaks Config - 1.19.2

# Setting a patch to false is equivalent to default behavior (i.e. it completely disables the fix and related modifications). If the per-module toggles are set to false, it will disable every patch below, regardless of the per-patch value. If true, it will respect the per-patch toggle

# All config changes requires restart

# Hi, if this mod ever updates and introduces new configs, please delete this config file and maybe save your changes so it can regenerate with the new config options. I don't actually know what I'm doing when it comes to this whole minecraft modding thing, so this is the best I can do for now, sorry for any inconveniences

celescolor=true
# Toggles celescolor, a clientside patch that adds the cyan-gold tooltip of celestial weapons from 1.20.1 to 1.19.2
# Will overwrite all other colors (i.e. Apotheosis reforges)


curios_fix=true
# Toggles all (attempted) fixes for Curios, which stops curios that either occupy transient slots (e.g. charms equipped in slots granted by Leather Belt from Relics) or curios that are condition-gated (e.g. charms exclusive to the Ring of the Seven Curses from Enigmatic Legacy) from unequipping upon relogging and/or respawning/dimension changes, which can prevent item loss in case of crashes or similar occurrences

#--------------------------------------------------
seven_curses=true
# [EXPERIMENTAL FIX] When true, forces isTheCursedOne to always be true before the player loads in, preventing curios that are exclusive to the Ring of the Seven Curses from auto-unequipping upon relogs. In theory, because this disables the moment the player logs, it should be impossible to exploit this to equip exclusive curios without the ring, but even if not, most Seven Curses exclusive curios have runtime checks
#--------------------------------------------------

enigmatic_addons=true
# Toggles all Enigmatic Addons-related patches

#--------------------------------------------------
primeval_impact=true
# "Wherever you go, whatever life throws at you...In Minecraft, the stars in the sky will always have a place for you"

# (The code requires a player close to the Primeval Cube. Please ensure that you are the nearest player to the cube you activated (a concern in multiplayer, since if someone is closer to your cube, they can potentially receive the acknowledgment of the cosmos instead) and that you are within 64 blocks of it, otherwise custom logic will not occur, and Primeval Cube will behave as if this was not enabled) Thanks, and happy rolling~

charm_of_malice=true
# When true, allows the Totem of Malice to be equipped in the charm slot
#--------------------------------------------------

enigmatic_legacy=true
# Toggles all Enigmatic Legacy-related patches

#--------------------------------------------------
harming_potion_fix=true
# When true, applies a "fix" that allows the spellstones which provide a form of effect immunity to also work on Splash Potions of Harming, the spellstones being Pearl of the Void, Non-Euclidean Cube, and Heart of Creation. (I'm unsure if this is intended, but considering it successfully blocks the instant_damage effect when applied using /effect, the splash potion should work the same

creation_heart_buff=true
# When true, gives the Heart of Creation +1 spellstone slots when equipped. Note: this patch also automatically overrides the SpellstonesMultiequip config option for Enigmatic Legacy to be true, otherwise this would be useless

intelligent_spellstones=true
# When true, the Non-Euclidean Cube and the Heart of Creation will not clear the negative effects defined below

# Format: [modid:effect_name], separate entries with commas
spellstone_blacklist=[l2complements:emerald_splash]

aggressive_cube=true
# When true, alters Non-Euclidean Cube logic to used tick-based enforcement to clear negative effects, like the Pearl of the Void and the Heart of Creation. Useful in some modpack contexts if certain negative effects are not cleared by the Cube. This can be disabled in vanilla, or if all negative effects in your Minecraft environment are properly neutralized by the Cube
#--------------------------------------------------

turkish_locale_fix=true
# [EXPERIMENTAL FIX] When true, toggles the clientside Turkish locale fix, which works by detecting if your locale is Turkish, and if so, sets it to ROOT. This might resolve crashes caused by Turkish OS / JVM locale. Only enable if you are experiencing crashes related to this issue

